image: dist.hosts.rfi:5000/dind:kub

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
services:
- name: docker:dind
  command: ["--insecure-registry=dist.hosts.rfi:5000"]

before_script:
- docker info

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - sh .ci-docker-build.sh $CI_JOB_STAGE $CI_PROJECT_NAME $CI_PROJECT_DIR $CI_PIPELINE_ID

deploy:
  stage: deploy
  script:
    - sh .ci-docker-build.sh $CI_JOB_STAGE $CI_PROJECT_NAME $CI_PROJECT_DIR $CI_PIPELINE_ID
    
